const data = [
    { id: 1, title: "Футболка", category: "Одежда", color: "Красный", cost: 20 },
    { id: 2, title: "Холодильник", category: "Бытовая техника", color: "Белый", cost: 500 },
    { id: 3, title: "Смартфон", category: "Электроника", color: "Черный", cost: 300 },
    { id: 4, title: "Блокнот", category: "Канцтовары", color: "Желтый", cost: 5 },
    { id: 5, title: "Джинсы", category: "Одежда", color: "Синий", cost: 40 },
    { id: 6, title: "Микроволновка", category: "Бытовая техника", color: "Серый", cost: 100 },
    { id: 7, title: "Наушники", category: "Электроника", color: "Белый", cost: 50 },
    { id: 8, title: "Карандаши", category: "Канцтовары", color: "Разноцветные", cost: 3 },
    { id: 9, title: "Платье", category: "Одежда", color: "Розовый", cost: 30 },
    { id: 10, title: "Пылесос", category: "Бытовая техника", color: "Желтый", cost: 120 },
    { id: 11, title: "Ноутбук", category: "Электроника", color: "Серебро", cost: 800 },
    { id: 12, title: "Тетрадь", category: "Канцтовары", color: "Зеленый", cost: 2 },
    { id: 13, title: "Куртка", category: "Одежда", color: "Черная", cost: 60 },
    { id: 14, title: "Плита", category: "Бытовая техника", color: "Белая", cost: 200 },
    { id: 15, title: "Смарт-часы", category: "Электроника", color: "Черный", cost: 100 },
    { id: 16, title: "Ручка", category: "Канцтовары", color: "Синяя", cost: 1 },
    { id: 17, title: "Пальто", category: "Одежда", color: "Коричневое", cost: 80 },
    { id: 18, title: "Холодильная камера", category: "Бытовая техника", color: "Серебро", cost: 1000 },
    { id: 19, title: "VR-очки", category: "Электроника", color: "Черный", cost: 150 },
    { id: 20, title: "Клей", category: "Канцтовары", color: "Прозрачный", cost: 4 },
    { id: 21, title: "Свитер", category: "Одежда", color: "Голубой", cost: 35 },
    { id: 22, title: "Миксер", category: "Бытовая техника", color: "Красный", cost: 80 },
    { id: 23, title: "Фотоаппарат", category: "Электроника", color: "Черный", cost: 200 },
    { id: 24, title: "Ластик", category: "Канцтовары", color: "Белый", cost: 1 },
    { id: 25, title: "Шляпа", category: "Одежда", color: "Желтая", cost: 15 }
]

